Parameters:
  AmiIdParam:
    Type: String
    Default: ami-8c1be5f6
    Description: AMI Id for the EC2 instance. Latest Amazon Linux is recommended

  InstanceTypeParam:
    Type: String
    Default: t2.nano
    Description: Enter an instance type for the EC2 instance.

  KeyNameParam:
    Type: String
    Default: sinatra
    Description: An AWS EC2 Key Name, must already exist

  SSHCidrParam:
    Type: String
    Default: 0.0.0.0/0
    Description: A source CIDR address to allow SSH connections from

Outputs:
  SinatraURL:
    Description: URL where the simple sinatra app can be accessed
    Value: !Join
      - ""
      - - "http://"
        - !GetAtt SinatraEc2.PublicIp

Resources:
  SinatraSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow traffic to sinatra app
      SecurityGroupIngress:
      - IpProtocol: tcp #Allow ssh from world
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref SSHCidrParam
      - IpProtocol: tcp #Allow sinatra from world
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  SinatraEc2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !Ref AmiIdParam
      InstanceType: !Ref InstanceTypeParam
      KeyName: !Ref KeyNameParam
      SecurityGroupIds:
        - !Ref SinatraSG
      UserData:
        !Base64 |
          #!/bin/bash
          #Start from an up-to-date base
          yum -y update

          #Install/config dependencies for the sinatra app
          # - git - to checkout the code with
          # - ruby2.2 - for the sinatra app
          yum -y install git ruby24

          #Use ruby2.2 by default
          alternatives --set ruby /usr/bin/ruby2.4

          #  - create a user to run the app as
          useradd -m sinatra

          #install and run the sinatra app
          su - sinatra << 'EOF'
          cd ~
          git clone https://github.com/rea-cruitment/simple-sinatra-app.git
          cd ~/simple-sinatra-app
          gem install bundler
          bundle install
          EOF

          #forward port 80 to sinatra app
          iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 9292
          iptables-save > /etc/sysconfig/iptables

          #run the sinatra app on startup
          cat << 'EOF' >> /etc/rc.d/rc.local
          su - sinatra -c "cd ~sinatra/simple-sinatra-app; rackup -o 0.0.0.0 >> ~sinatra/sinatra.log 2>&1 &"
          EOF
